server:
  port: 8000

spring:
  application:
    name: msa-service-gateway

  cloud:
    gateway:
      routes:
        #1      [USER-SERVICE]
        - id: user-service
          uri: lb://MSA-SERVICE-USER
          predicates:
            - Path=/msa/service/user/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/msa/service/user(?<segment>.*), /$\{segment}
            - CustomFilter

        - id: user-service
          uri: lb://MSA-SERVICE-USER
          predicates:
            - Path=/msa/service/user/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/msa/service/user(?<segment>.*), /$\{segment}
            - CustomFilter

        - id: user-service
          uri: lb://MSA-SERVICE-USER
          predicates:
            - Path=/msa/service/user/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/msa/service/user(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: user-service
          uri: lb://MSA-SERVICE-USER
          predicates:
            - Path=/msa/service/user/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/msa/service/user(?<segment>.*), /$\{segment}


        #2      [CATALOG-SERVICE]
        - id: catalog-service
          uri: lb://MSA-SERVICE-CATALOG
          predicates:
            - Path=/msa/service/catalog/**
          filters:
            - RewritePath=/msa/service/catalog(?<segment>.*), /$\{segment}
            - CustomFilter
        #3      [ORDER-SERVICE]
        - id: order-service
          uri: lb://MSA-SERVICE-ORDER
          predicates:
            - Path=/msa/service/order/**
          filters:
            - RewritePath=/msa/service/order(?<segment>.*), /$\{segment}
            - CustomFilter
        #4      [CONFIG-SERVICE]
        - id: config-service
          uri: lb://MSA-SERVICE-CONFIG
          predicates:
            - Path=/msa/service/config/**
          filters:
            - RewritePath=/msa/service/config(?<segment>.*), /$\{segment}
            - CustomFilter


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
