server:
  port: 8761

spring:
  application:
    name: msa-service-discovery

  eureka:
    client:
      enabled: false  # Eureka ???? ????? ?? ????
    server:
      enableSelfPreservation: false  # ???? false? ???? ????? ????? ?????.
