server:
  port: 8888

spring:
  application:
    name: msa-service-config

  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joneconsulting/spring-cloud-config


  file:///path/to/your/config-repo