server:
  port: 8888

spring:
  application:
    name: msa-service-config
  eureka:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
